name: CI - Build and Publish Worker Docker Image

on:
  push:
    branches:
      - master  # Execute a pipeline quando houver push na branch principal

env:
  csproj: MyWorker.csproj
  IMAGE_NAME: myworker
  IMAGE_TAG: latest
  DEVSECOPS_REPOSITORY: devsecops-relatorios  # Nome do repositório centralizado

jobs:
  build:
    runs-on: ubuntu-latest  # Executa em uma máquina virtual com Ubuntu
    
    steps:
    
    # Etapa 1: Checkout do código
    - name: Checkout code
      uses: actions/checkout@v3

    # Etapa 2: Build da imagem Docker
    - name: Build Docker image
      run: |
        docker build --build-arg CSPROJ="$CSPROJ" -t $IMAGE_NAME:$IMAGE_TAG .

    # Etapa 3: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Etapa 4: Push da imagem Docker
    - name: Push Docker image
      run: |
        docker tag $IMAGE_NAME:$IMAGE_TAG ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$IMAGE_TAG
        docker push ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$IMAGE_TAG

    # Etapa 5: Install Trivy
    - name: Install Trivy
      run: |
        curl -sSfL https://github.com/aquasecurity/trivy/releases/download/v0.38.3/trivy_0.38.3_Linux-64bit.deb -o trivy.deb
        sudo dpkg -i trivy.deb
        sudo apt-get update

    # Etapa 6: Run Trivy to scan Docker image for vulnerabilities
    - name: Run Trivy to scan Docker image for vulnerabilities
      run: |
        trivy image --format json --output trivy-report.json ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$IMAGE_TAG

    # Etapa 7: Commit and push the Trivy report to the devsecops-relatorios repository
    - name: Push Trivy Report to devsecops-relatorios repository
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub token to authenticate
      run: |
        # Adiciona o repositório devsecops-relatorios como remoto
        git clone https://github.com/${{ github.repository_owner }}/$DEVSECOPS_REPOSITORY.git
        cd $DEVSECOPS_REPOSITORY

        # Cria um novo diretório com o nome da imagem e tag
        mkdir -p trivy-reports/$IMAGE_NAME/$IMAGE_TAG
        
        # Copia o relatório Trivy para o diretório criado
        cp ../trivy-report.json trivy-reports/$IMAGE_NAME/$IMAGE_TAG/

        # Configura o usuário de commit para o GitHub Actions
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions@github.com"
        
        # Faz commit e push
        git add .
        git commit -m "Adicionar relatório Trivy para $IMAGE_NAME:$IMAGE_TAG"
        git push origin main
