name: CI - Build and Publish Worker Docker Image

on:
  push:
    branches:
      - main  # Execute a pipeline quando houver push na branch principal

env:
  csproj: MyWorker.csproj
  IMAGE_NAME: myworker
  IMAGE_TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest  # Executa em uma máquina virtual com Ubuntu
    
    steps:
    
    # Etapa 1: Checkout do código
    - name: Checkout code
      uses: actions/checkout@v3

    # Etapa 2: Build da imagem Docker
    - name: Build Docker image
      run: |
        docker build --build-arg CSPROJ="$CSPROJ" -t $IMAGE_NAME:$IMAGE_TAG .

    # Etapa 3: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Usando o secret de username
        password: ${{ secrets.DOCKER_PASSWORD }}  # Usando o secret de password

    # Etapa 4: Push da imagem Docker
    - name: Push Docker image
      run: |
        docker tag $IMAGE_NAME:$IMAGE_TAG ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$IMAGE_TAG
        docker push ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$IMAGE_TAG
